wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 5000
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682238663.025096
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.14.2
      8:
      - 3
      - 5
